### ISSUE TITLE
PNGs don't get rendered

### ISSUE THREAD

**Issue by LeBar** [Widgetlabs/gradle-android-svg#3]
When integrating the plugin into our build process the directories get created but never filled with any PNG. The source as well as the destination directory for each density get printed to the output but no rendering part.

**Comment by martyglaubitz** [comment]
@LeBar running a *clean* should fix this

**Comment by LeBar** [comment]
Thanks for the tip but it doesn't work either.

The log says:
[...]
Executing task ':app:renderXxhdpiSvg' (up-to-date check took 0.003 secs) due to:
  Input file ***/app/svg/join.svg has been added.
  Input file ***/app/svg/join_old.svg has been removed.
Starting process 'command 'convert''. Working directory: ***/app Command: convert -resize 300.000% ***/app/svg/join.svg ***/app/src/main/res/drawable-xxhdpi/join.png
[...]

But no file gets created.

**Comment by martyglaubitz** [comment]
@LeBar oh well, there's that imagemagick issue again :( Ifu just want fix to work, you could try out: https://github.com/avianey/androidsvgdrawable-plugin I haven't got the time to fix the plugin yet...

**Comment by LeBar** [comment]
That did it - I just installed imagemagick and everything is working fine now. You should just add this to your readme so others can fix it for themselves for now.

Thanks for your help! ;)

**Comment by martyglaubitz** [comment]
@LeBar this plugin is not mainted anymore, please use the mutch nicer implemented and working https://github.com/avianey/androidsvgdrawable-plugin
